### ISSUE TITLE
不建议用在正式项目

### ISSUE THREAD

**Issue by linlinyao1** [winddpan/CodableWrapper#1]
因为用到了mirror反查系统内部属性，thread注入参数这些不稳定的实现。和swift追求静态语言的原则不太符，活活把swift写错了oc

**Comment by winddpan** [comment]
> 因为用到了mirror反查系统内部属性，thread注入参数这些不稳定的实现。和swift追求静态语言的原则不太符，活活把swift写错了oc

1. 作为参考， [HandyJSON](https://github.com/alibaba/HandyJSON) 作为一个使用范围广泛的库，使用Mirror和MemoryLayout来分布实现读写，显得更加不'Swifty'。
2. CodoableWrapper基于Swift开源代码 [JSONEncoder.swift](https://github.com/apple/swift/blob/88b093e9d77d6201935a2c2fb13f27d961836777/stdlib/public/Darwin/Foundation/JSONEncoder.swift) [ Codable.swift](https://github.com/apple/swift/blob/248c554524391f57617047364728103dcc0dcf12/stdlib/public/core/Codable.swift) 在适当时机做了一些“注入”，只要Codable源码不变就不需要变更核心逻辑，相比HanyJSON会更加稳定一些。
3. CodoableWrapper的出现跟HandyJSON遇到最近几次iOS系统版本更新闪退有一定关系。
4. 作为一个新出炉的库，肯定会有一些不足，如果在使用过程中遇到问题，欢迎讨论。

**Comment by rakuyoMo** [comment]
2022年12月27日，和伙伴研究了一下这个库的实现，感觉没有什么大的问题，用在正式项目里应该是安全且可靠的。@winddpan 大佬给力。
