### ISSUE TITLE
pod search CodableWrapper 没有最新的0.3.3

### ISSUE THREAD

**Issue by Channe** [winddpan/CodableWrapper#14]
-> CodableWrapper (0.3.2)
   Codable + PropertyWrapper
   pod 'CodableWrapper', '~> 0.3.2'
   - Homepage: https://github.com/winddpan/CodableWrapper
   - Source:   https://github.com/winddpan/CodableWrapper.git
   - Versions: 0.3.2, 0.3.1, 0.3.0, 0.2.5, 0.2.0, 0.1.2, 0.1 [cocoapods repo]

**Comment by winddpan** [comment]
updated
