### ISSUE TITLE
自定义解析依赖其他的属性怎么处理呀？

### ISSUE THREAD

**Issue by kellenyangs** [winddpan/CodableWrapper#18]
struct Article {
    @Codec var type: String?
    @Codec var title: String?
    @Codec var info: Info?
    @Codec var desc: String?
    @Codec var createAt: String?
}

比如 info 的内容取决于 type的类型

**Comment by kellenyangs** [comment]
在求教一下，如果我要在解析完后执行某个方法，该怎么实现呢？

**Comment by winddpan** [comment]
本库只是Codable Encode/Decode一个中转处理层，没有添加额外能力。
这个例子你可以使用计算属性。
建议先了解Codable后再使用本库。
