### ISSUE TITLE
property wrapper的限制

### ISSUE THREAD

**Issue by alexlee002** [winddpan/CodableWrapper#2]
遇到几个问题：
1， 如果一个model， 在不同的场合下要转换成不同的JSON， 这个怎么处理？
2，property wrapper无法嵌套， 如果用了这个库， 那么model里边就没办法再使用其它库的property wrapper了。

**Comment by winddpan** [comment]
1. 如果要根据业务使用不同的key，势必要在encode方法调用时加入参数增加复杂度，目前无这方面的计划。另外HandyJSON也是单向的。
2. CodableWrapper放前面，后面的PropertyWrapper实现Codable协议即可，就像这样
```
@propertyWrapper
struct OtherWrapper: Codable {
  ...
}

struct Model {
  @CodableWrapper @OtherWrapper
  var value: String
}
```

**Comment by alexlee002** [comment]
1. 第一个需求， 貌似是通过property wraspper是无法满足的， 但是如果能在转换的时候传入一个自定义的map， 应该是能实现的
2. 第二个场景，对于自己实现的propertyWrapper没问题， 但是对于其他第三方库的实现就很难兼容了， 其实这个就限制了property wrapper的应用。
