### ISSUE TITLE
model里面有state，就运行不起来

### ISSUE THREAD

**Issue by wscqs** [winddpan/CodableWrapper#23]
@Codable
class BaseModel{
    var errorno: Int = -1
    var error: String = ""
//    var state: String?//有state参数就运行不起来
}

**Comment by winddpan** [comment]
Swift宏的bug，注释不要写到同一行
```
// 写这里
var state: String?
```

**Comment by wscqs** [comment]
来信已经收到。

**Comment by wscqs** [comment]
真是注释的问题。谢谢，我关闭问题
