### ISSUE TITLE
希望能支持cocoapods引用1.0.0版本

### ISSUE THREAD

**Issue by zhtut** [winddpan/CodableWrapper#26]
如题
现在的项目，都是从历史来的，要完全脱离cocoapods还是很难的，但是我们的版本是符合的，最低安装版本为iOS13，我们希望能在新需求中，使用swift5.9的新特性来解析codable，以提高解析安全性。如果cocoapods和spm混用的话，那我的cocoapods子库无法引用到CodableWrapper，所以只能使用cocoapods来接入。
如果CodableWrapper的cocoapods的版本不能更新，那我们不会考虑接入CodableWrapper
希望作者考虑一下这个问题，感谢！

**Comment by winddpan** [comment]
pod 'CodableWrapper', :git => 'https://github.com/winddpan/CodableWrapper.git', :branch => '1.1.0'

[Beta 1.1.0](https://github.com/winddpan/CodableWrapper/tree/1.1.0)
