### ISSUE TITLE
Unknown attribute 'Codec'

### ISSUE THREAD

**Issue by yangguanghei** [winddpan/CodableWrapper#3]
use "@Codec var stringVal: String = "OK""
error: "Unknown attribute 'Codec'"

**Comment by Scyano** [comment]
@Codec 大写
然后你看下是不是忘记导入库了 `import CodableWrapper`

**Comment by yangguanghei** [comment]
> 你看下是不是忘记导入库了 `import CodableWrapper`

刚发现是版本号的问题，无法怎么pod repo update，索引库中最新的版本号多是0.1.2

**Comment by Scyano** [comment]
忘了 push podspec 了, 抱歉😅😅😅
最近用的 SPM, 有点日子没用 `cocoapods` 了

**Comment by yangguanghei** [comment]
> 忘了 push podspec 了, 抱歉😅😅😅
> 最近用的 SPM, 有点日子没用 `cocoapods` 了

后来直接下载源码了😄，顺便了解了下你说的SPM（Swift Package Manager ）
