### ISSUE TITLE
xcode run 一直过不去

### ISSUE THREAD

**Issue by nashht** [winddpan/CodableWrapper#30]
在一些简单的model添加了 @Codable 宏后，xcode run的时候一直过不去，很奇怪为什么 ，也不报错

**Comment by winddpan** [comment]
能提供一个能复现的最小化 demo 吗？

**Comment by nashht** [comment]
> 能提供一个能复现的最小化 demo 吗？

[TestCodableWrapper.zip](https://github.com/winddpan/CodableWrapper/files/15057483/TestCodableWrapper.zip)
XCode15.3 这个demo 在我这里稳定复现

**Comment by winddpan** [comment]
SwiftMacro的bug，注释不要写一行。
```
@Codable
struct PushCustomData {
    var url: String? // 消息对应的 Scheme
}

改成

@Codable
struct PushCustomData {
    // 消息对应的 Scheme
    var url: String?
}
```
