### ISSUE TITLE
为什么一直在编译？

### ISSUE THREAD

**Issue by Gaozn** [winddpan/CodableWrapper#31]
pod 'CodableWrapper', :git => 'https://github.com/winddpan/CodableWrapper.git', :branch => '1.1.0'
  Version 15.0.1 (15A507)

耗时，cpu拉满，升温，编译失败

**Comment by winddpan** [comment]
错误信息能发一下吗？

**Comment by a594508257** [comment]
> pod 'CodableWrapper', :git => 'https://github.com/winddpan/CodableWrapper.git', :branch => '1.1.0' Version 15.0.1 (15A507)
> 
> 耗时，cpu拉满，升温，编译失败

耗时问题在于需要将宏定义编译成二进制产物，首次编译会额外占用大约170s的时间，二进制编译成功后编译项目就不会占用时间了，二进制产物会跟随项目的Clean。编译失败可能是因为二进制编译的阶段停止了项目编译，再次编译导致的线程错误，建议clean之后开始编译直到结束，不要停止再重新编译

**Comment by winddpan** [comment]
检查是不是注释的写法问题
https://github.com/winddpan/CodableWrapper/issues/30#issuecomment-2068554658

**Comment by Gaozn** [comment]
检查确实是这个问题。已解决 多谢
