### ISSUE TITLE
与 wcdb.swift 一起使用，@Codec 与 wcdb的 tablecodable 中 coding定义 导致崩溃

### ISSUE THREAD

**Issue by yonfong** [winddpan/CodableWrapper#6]
`struct ExaminationItem: Codable {
    static let tableName = "ExamTable"
    
    var id: String
    var type: String
    var typename: String
    var fathertype: String
    var fathertypename: String
    var searchwd: String?
    var biaozhu: String?
    

    var timu: [ExamOptionItem] = []
    var xuanxiang: [ExamOptionItem] = []
    var jiexi: [ExamOptionItem] = []
    var daan: [String] = []
    
    @Codec var showAnalyze: Bool = false
    @Codec var isshoucang: Bool = false
    @Codec var timuleibie: Bool = false
    
    var noXunxiang: Bool {
        get {
            return daan.count <= 0
        }
    }
    
    var isRadio: Bool {
        get {
            return daan.count <= 1
        }
    }
}
extension ExaminationItem: TableCodable {
    enum CodingKeys: String, CodingTableKey {
        typealias Root = ExaminationItem
        static let objectRelationalMapping = TableBinding(CodingKeys.self)
        case id
        case type
        case typename
        case fathertype
        case fathertypename
        case searchwd
        case biaozhu
        case timu
        case xuanxiang
        case jiexi
        case daan
        case isshoucang
        case timuleibie
    }
}`

<img width="1421" alt="截屏2021-11-14 下午2 18 01" src="https://user-images.githubusercontent.com/33693428/141670040-95d65325-25a0-49a4-b3a5-06777850d3f8.png">

请教下 需要怎么解决

**Comment by Scyano** [comment]
主线程调用栈栈顶是 Dictionary.vatiant.subscript.getter 吗

**Comment by Scyano** [comment]
WCDB 内使用 `KeyedDecodingTableContainer<CodingKeys: CodingKey>`, 与原生 KeyedDecodingContainer 内存布局不同, 导致获取 _container 时 crash, 确实是个隐患. 感谢反馈, 会尽快解决的

**Comment by yonfong** [comment]
> WCDB 内使用 `KeyedDecodingTableContainer<CodingKeys: CodingKey>`, 与原生 KeyedDecodingContainer 内存布局不同, 导致获取 _container 时 crash, 确实是个隐患. 感谢反馈, 会尽快解决的

请问下 这个问题是不是还没解决？

**Comment by winddpan** [comment]
> > WCDB 内使用 `KeyedDecodingTableContainer<CodingKeys: CodingKey>`, 与原生 KeyedDecodingContainer 内存布局不同, 导致获取 _container 时 crash, 确实是个隐患. 感谢反馈, 会尽快解决的
> 
> 请问下 这个问题是不是还没解决？

没有解决，WCDB很难兼容，短期不再处理

**Comment by yonfong** [comment]
@winddpan 您好，项目重度依赖 CodableWrapper 和 WCDBSwift，麻烦您再研究下这个问题看看是否能解决吗？谢谢！

**Comment by mancongiOS** [comment]
WCBD内部重写了Codable相关的协议，CodableWrapper内部也重写了导致了调用冲突， 这代表着只要有相关实现的三方库都会产生这样的问题。 这个问题在现有的逻辑下没法解决。 要想彻底解决，就只能完整的重写JSONDecoder和JSONEncoder这两个解析器，而不是重写Codable相关的协议方法。
